name: issue template
description: register new issue
labels: []
assignees: [c99-coder, seungjae94, kimhyeongjun95, tnghd5761]

body:
- type: textarea
  attributes:
    label: 목적
    description: 이슈를 남기는 목적이 무엇인가요?
    options:
    - value: |
        >
      required: true
      
- type: textarea
  attributes:
    label: 작업 내용
    description: 어떤 작업을 했나요?
    options:
    - value: |
        - [ ] 
      required: true

- type: textarea
  attributes:
    label: 참고 사항
    options:
    - value: |
        -
      required: false
