name: issue template
description: register new issue
labels: []
assignees: [c99-coder, seungjae94, kimhyeongjun95, tnghd5761]

body:
- type: markdown
  attributes:
    value: |
      "## 목적"
      >
- type: textarea
  attributes:
    label: "Objective"
    value: |
      >
  validations:
    required: true
- type: textarea
  attributes:
    label: 작업 내용
    description: 어떤 작업을 했나요?
    value: |
      - [ ] 
  validations:
    required: true
- type: textarea
  attributes:
    label: 참고 사항
    description: 따로 참고할 만한 사항이 있나요?
    value: |
      -
  validations:
    required: false
